# Generated by Django 5.2 on 2025-05-06 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_person_first_name_remove_person_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_data_types', to='core.persondatatype'),
        ),
    ]
