# Generated by Django 5.2 on 2025-05-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_persondata_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='types',
            field=models.ManyToManyField(blank=True, null=True, related_name='persons', to='core.persontype'),
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(blank=True, null=True),
        ),
    ]
