# Generated by Django 5.2 on 2025-05-06 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_person_types_alter_work_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondata',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_data_types', to='core.persondatatype'),
        ),
    ]
